version: '3'
services:
  elasticsearch7x:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch7x
    ports:
      - 9202:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms400m -Xmx400m
  kibana7x:
    image: docker.elastic.co/kibana/kibana:7.7.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch7x:9200
    ports:
      - 5602:5601
    depends_on:
      - elasticsearch7x
  elasticsearch-migrate:
    image: kmiura1002/elasticsearch-index-migrate:0.4.1
    volumes:
      - "./sample:/sample"
    depends_on:
      - elasticsearch7x
    links:
      - elasticsearch7x
    working_dir: /sample